name: Build
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Personal OS image based on Fedora Silverblue"
  REGISTRY_USER: "${{ github.actor }}"
  REGISTRY_PASSWORD: "${{ github.token }}"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  GH_REPO: "${{ github.repository }}"
  GH_REF_TYPE: "${{ github.ref_type }}"
  GH_REF_NAME: "${{ github.ref_name }}"
  GH_PR: "${{ github.event.number }}"

jobs:
  variants:
    name: Prepare list of variants
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      variants: ${{ steps.json.outputs.variants }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Load variants
        id: json
        run: |
          output=$(bun script/list-variants.ts)
          echo "variants=$output" >> $GITHUB_OUTPUT

  build_push:
    name: Build and push image
    runs-on: blacksmith-4vcpu-ubuntu-2204

    permissions:
      contents: read
      packages: write
      id-token: write

    needs: variants
    strategy:
      matrix:
        variant: ${{ fromJson(needs.variants.outputs.variants) }}

    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          sudo apt install -y dbus-x11
          sudo loginctl enable-linger 1000
          bun install

      - name: Build and push image
        run: bun script/build-image.ts ${{ matrix.variant }}
